"use client"

import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { AppHeader } from "@/components/layout/app-header";
import { EventPersponsive } from "@/components/shared/event-responsive";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState } from "react";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"],
});

// export const metadata: Metadata = {
//   title: "Next Said Test App",
//   description: "Generated by create said developer",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [queryClient] = useState(() => new QueryClient());
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>
        <QueryClientProvider client={queryClient}>
          <SidebarProvider>
            <AppSidebar />
            <main className="pt-9 relative overflow-hidden px-5 w-full">
              <AppHeader />
              {children}
            </main>
            <EventPersponsive />
          </SidebarProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
