import {
  InputOTP,
  InputOTPGroup,
  InputOTPSlot,
} from "@/components/ui/input-otp";
import Image from "next/image";
import { motion } from "framer-motion";



export const Verification = () => {
  return (
    <motion.div
    key="verification"
    initial={{ opacity: 0, y: -20 }}
    animate={{ opacity: 1, y: 0 }}
    exit={{ opacity: 0, y: 20 }}
    transition={{ duration: 0.2 }}
    className="p-6 rounded-2xl w-full flex flex-col gap-6 shadow bg-background border max-w-[520px] mx-auto">
      <div className="mx-auto">
        <Image src={"/varify-pic.png"} alt="Verify svg" width={70} height={70} className="h-auto w-[70px]"/>
      </div>
      <h2 className="text-3xl text-center">Verificate Your Account</h2>
      <p className=" text-center">
        Enter the code generated by your 2-factor aut App
      </p>
      <InputOTP maxLength={6}>
        <InputOTPGroup className="mx-auto justify-between w-full max-w-[360px]">
          <InputOTPSlot index={0} />
          <InputOTPSlot index={1} />
          <InputOTPSlot index={2} />
          <InputOTPSlot index={3} />
          <InputOTPSlot index={4} />
          <InputOTPSlot index={5} />
        </InputOTPGroup>
      </InputOTP>
    </motion.div>
  );
};
